#!/bin/bash

# Shell
export HISTCONTROL=erasedups                # erase duplicates
export HISTSIZE=20000                       # resize history size
export BASH_SILENCE_DEPRECATION_WARNING=1   # disable macos zsh alert
bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"

# Import .bashrc if present
#[[ -r ~/.bashrc ]] && source ~/.bashrc

# Homebrew
export PATH="/usr/local/sbin:$PATH"

# Node
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Deno
export PATH="~/.deno/bin:$PATH"

# Perl
PATH="/Users/danyalaytekin/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/Users/danyalaytekin/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/danyalaytekin/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Users/danyalaytekin/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/danyalaytekin/perl5"; export PERL_MM_OPT;

# Autojump
[[ -f $(brew --prefix)/etc/profile.d/autojump.sh ]] && source $(brew --prefix)/etc/profile.d/autojump.sh

# Ruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby-2.5.3

# Python 3 (use Homebrew version)
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Git
source /usr/local/etc/bash_completion.d/git-completion.bash
source /usr/local/etc/bash_completion.d/git-prompt.sh

# Prompt
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWCOLORHINTS=true
PS1="\n\u, \W\$(__git_ps1) > "

# Aliases for shell
alias aj="autojump"
alias bu="brew update && brew upgrade && brew prune && brew doctor"
alias bye="exit"
alias c="clear"
alias clear="clear && quoth"
alias db="dotnet build"
alias dr="dotnet run"
alias e="exit"
alias g="googler"
alias gca="git commit --amend"
alias ls="ls -la"
alias q="quoth"
alias nl="npm list --depth=0"
alias ns="npm start"
alias npm2="npm run lint && npm test"

# Aliases for git
alias commit="git commit -m"
alias pull="git pull"
alias push="git push"

# Aliases for programs
alias 1password="open -a 1password"
alias bear="open -a Bear"
alias chrome="open -a google\ chrome"
alias chrome_without_web_security="open -a google\ chrome --args --disable-web-security --user-data-dir"
alias contacts="open -a contacts"
alias outlook="open -a microsoft\ outlook"
alias safari="open -a safari"
alias simulator="open -a simulator"
alias teams="open -a firefox https://teams.microsoft.com"
alias web="safari"
