#!/bin/bash

# Shell
export HISTCONTROL=erasedups    # erase duplicates
export HISTSIZE=20000           # resize history size
bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"

# ensure .bashrc is read
#[[ -r ~/.bashrc ]] && . ~/.bashrc

# Node
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Autojump
[[ -f $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# Ruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby-2.5.1

# Python 3 (use Homebrew version)
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# Git
source /usr/local/etc/bash_completion.d/git-completion.bash
source /usr/local/etc/bash_completion.d/git-prompt.sh

# Prompt
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWCOLORHINTS=true
PS1="\n\u, \W\$(__git_ps1) > "

# Aliases for shell
alias aj="autojump"
alias bu="brew update && brew upgrade && brew prune && brew doctor"
alias bear="open /Applications/Bear.app"
alias bye="exit"
alias c="clear"
alias clear="clear && quoth"
alias db="dotnet build"
alias dr="dotnet run"
alias e="exit"
alias g="googler"
alias gc="git commit -am"
alias gca="git commit --amend"
alias ls="ls -la"
alias q="quoth"
alias nl="npm list --depth=0"
alias ns="npm start"
alias npm2="npm run lint && npm test"

# Aliases for programs
alias 1password="open -a 1password"
alias chrome="open -a google\ chrome"
alias chrome_without_web_security="open -a google\ chrome --args --disable-web-security --user-data-dir"
alias contacts="open -a contacts"
alias outlook="open -a microsoft\ outlook"
alias safari="open -a safari"
alias tidal="open -a tidal"
alias web="safari"
